### PR TITLE
add video to site

### PR DESCRIPTION
**Pull request by natdudley**
add an include for video inclusion, and then add id to page

this enables us to embed the launch video on the about page.

### CODE REVIEW

**Comment by robisaacnz** [comment]
Rejecting for now: OpenGraph meta tags in `intro.html` specify a localhost URL, which won't render correctly when served from GitHub Pages.

**Comment by natdudley** [comment]
that seems weird.

**Comment by natdudley** [comment]
The site should build them correctly, it's using a relative path.

```<meta property="og:image" content="{{site.url}}/assets/img/layout/open-graph.jpeg" >```

**Comment by natdudley** [comment]
image

**Comment by robisaacnz** [comment]
Wait, is "_site" a rendered version of the site that somehow ended up in the repository, maybe?

**Comment by natdudley** [comment]
It is. It shouldn't be and I keep trying to exclude the whole damn folder from being committed, but failing. GitHub builds its own version of the _site folder on deploy.

**Pull request merged**
